"""Corrections

Revision ID: 0f3b3673531d
Revises: 6525790c51d5
Create Date: 2023-12-20 11:36:05.557742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3b3673531d'
down_revision = '6525790c51d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('block_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_address', sa.VARCHAR(length=42), autoincrement=False, nullable=True),
    sa.Column('receiver_address', sa.VARCHAR(length=42), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_gas_cost', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nonce', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gas', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('gasPrice', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_token_sending', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('token_recipient', sa.VARCHAR(length=42), autoincrement=False, nullable=True),
    sa.Column('token_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('token_symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pending_transaction_pkey')
    )
    # ### end Alembic commands ###
