"""Corrections

Revision ID: 2ca4c2b78cc9
Revises: 07e5542bfb5f
Create Date: 2023-12-02 16:28:37.675044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca4c2b78cc9'
down_revision = '07e5542bfb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gasPrice', sa.Integer(), nullable=True))
        batch_op.drop_column('gas_used')
        batch_op.drop_column('gas_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gas_price', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gas_used', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('gasPrice')
        batch_op.drop_column('gas')

    # ### end Alembic commands ###
