"""Corrections

Revision ID: 6525790c51d5
Revises: 20bed0ff826a
Create Date: 2023-12-11 21:26:43.424164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6525790c51d5'
down_revision = '20bed0ff826a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_transaction', schema=None) as batch_op:
        batch_op.alter_column('gasPrice',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_transaction', schema=None) as batch_op:
        batch_op.alter_column('gasPrice',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
